spring:
  liquibase:
    enabled: true
    user: postgres
    password: postgres
  datasource:
    url: 'jdbc:postgresql://localhost:5432/'
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  mail:
    host: 'localhost'
    port: 1025

token:
  secret-key: JUST_RANDOM_SECRET_KEY@@
